heat_template_version: queens
description: >
  Software Config to drive os-net-config to configure VLANs for the Compute1 role.

parameters:
  # ---------------------------------------------------------------------------
  # Supernets
  # ---------------------------------------------------------------------------
  ExternalSupernet:
    default: ''
    type: string
  InternalApiSupernet:
    description: InternalApiSupernet
    type: string
  StorageMgmtSupernet:
    description: StorageMgmtSupernet
    type: string
  StorageSupernet:
    description: StorageSupernet
    type: string
  TenantSupernet:
    description: TenantSupernet
    type: string
  CtlplaneSupernet:
    description: CtlplaneSupernet
    type: string

  # ---------------------------------------------------------------------------
  # Default Routes
  # ---------------------------------------------------------------------------
  ControlPlane0DefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ControlPlane1DefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ControlPlane2DefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ControlPlane3DefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string

  Tenant0InterfaceDefaultRoute:
    description: TenantInterfaceDefaultRoute
    type: string
  Tenant1InterfaceDefaultRoute:
    description: TenantInterfaceDefaultRoute
    type: string
  Tenant2InterfaceDefaultRoute:
    description: TenantInterfaceDefaultRoute
    type: string
  Tenant3InterfaceDefaultRoute:
    description: TenantInterfaceDefaultRoute
    type: string

  InternalApi0InterfaceDefaultRoute:
    description: InternalApiInterfaceDefaultRoute
    type: string
  InternalApi1InterfaceDefaultRoute:
    description: InternalApiInterfaceDefaultRoute
    type: string
  InternalApi2InterfaceDefaultRoute:
    description: InternalApiInterfaceDefaultRoute
    type: string
  InternalApi3InterfaceDefaultRoute:
    description: InternalApiInterfaceDefaultRoute
    type: string

  StorageMgmt0InterfaceDefaultRoute:
    description: StorageMgmtInterfaceDefaultRoute
    type: string
  StorageMgmt1InterfaceDefaultRoute:
    description: StorageMgmtInterfaceDefaultRoute
    type: string
  StorageMgmt2InterfaceDefaultRoute:
    description: StorageMgmtInterfaceDefaultRoute
    type: string
  StorageMgmt3InterfaceDefaultRoute:
    description: StorageMgmtInterfaceDefaultRoute
    type: string

  Storage0InterfaceDefaultRoute:
    description: StorageInterfaceDefaultRoute
    type: string
  Storage1InterfaceDefaultRoute:
    description: StorageInterfaceDefaultRoute
    type: string
  Storage2InterfaceDefaultRoute:
    description: StorageInterfaceDefaultRoute
    type: string
  Storage3InterfaceDefaultRoute:
    description: StorageInterfaceDefaultRoute
    type: string

  # External network is not routed, only one entry.
  External1InterfaceDefaultRoute:
    description: default route for the external network
    type: string

  # ---------------------------------------------------------------------------
  # IP subnets
  # ---------------------------------------------------------------------------
  Storage0IpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  Storage1IpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  Storage2IpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  Storage3IpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string

  StorageMgmt0IpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt network
    type: string
  StorageMgmt1IpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt network
    type: string
  StorageMgmt2IpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt network
    type: string
  StorageMgmt3IpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt network
    type: string

  InternalApi0IpSubnet:
    default: ''
    description: IP address/subnet on the internal_api network
    type: string
  InternalApi1IpSubnet:
    default: ''
    description: IP address/subnet on the internal_api network
    type: string
  InternalApi2IpSubnet:
    default: ''
    description: IP address/subnet on the internal_api network
    type: string
  InternalApi3IpSubnet:
    default: ''
    description: IP address/subnet on the internal_api network
    type: string

  Tenant0IpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  Tenant1IpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  Tenant2IpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  Tenant3IpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string

  External1IpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  ManagementIpSubnet:
    default: ''
    description: IP address/subnet on the management network
    type: string

  # ---------------------------------------------------------------------------
  # VLAN IDs
  # ---------------------------------------------------------------------------
  Storage0NetworkVlanID:
    default: 630
    description: Vlan ID for the storage network traffic.
    type: number
  Storage1NetworkVlanID:
    default: 631
    description: Vlan ID for the storage1 network traffic.
    type: number
  Storage2NetworkVlanID:
    default: 632
    description: Vlan ID for the storage network traffic.
    type: number
  Storage3NetworkVlanID:
    default: 633
    description: Vlan ID for the storage1 network traffic.
    type: number

  StorageMgmt0NetworkVlanID:
    default: 640
    description: Vlan ID for the storage_mgmt network traffic.
    type: number
  StorageMgmt1NetworkVlanID:
    default: 641
    description: Vlan ID for the storage_mgmt1 network traffic.
    type: number
  StorageMgmt2NetworkVlanID:
    default: 642
    description: Vlan ID for the storage_mgmt network traffic.
    type: number
  StorageMgmt3NetworkVlanID:
    default: 643
    description: Vlan ID for the storage_mgmt1 network traffic.
    type: number

  InternalApi0NetworkVlanID:
    default: 610
    description: Vlan ID for the internal_api network traffic.
    type: number
  InternalApi1NetworkVlanID:
    default: 611
    description: Vlan ID for the internal_api1 network traffic.
    type: number
  InternalApi2NetworkVlanID:
    default: 612
    description: Vlan ID for the internal_api network traffic.
    type: number
  InternalApi3NetworkVlanID:
    default: 613
    description: Vlan ID for the internal_api1 network traffic.
    type: number

  Tenant0NetworkVlanID:
    default: 650
    description: Vlan ID for the tenant network traffic.
    type: number
  Tenant1NetworkVlanID:
    default: 651
    description: Vlan ID for the tenant1 network traffic.
    type: number
  Tenant2NetworkVlanID:
    default: 652
    description: Vlan ID for the tenant network traffic.
    type: number
  Tenant3NetworkVlanID:
    default: 653
    description: Vlan ID for the tenant1 network traffic.
    type: number

  External1NetworkVlanID:
    default: 621
    description: Vlan ID for the external network traffic.
    type: number

  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number


  # ---------------------------------------------------------------------------
  # Subnet CIDR's - prefixes
  # ---------------------------------------------------------------------------
  ControlPlane0SubnetCidr: # Override this via parameter_defaults
    default: '26'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlane1SubnetCidr: # Override this via parameter_defaults
    default: '26'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlane2SubnetCidr: # Override this via parameter_defaults
    default: '26'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlane3SubnetCidr: # Override this via parameter_defaults
    default: '26'
    description: The subnet CIDR of the control plane network.
    type: string

  # ---------------------------------------------------------------------------
  # EC2 metadata server IPs
  # ---------------------------------------------------------------------------
  ControlPlane0EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  ControlPlane1EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  ControlPlane2EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
  ControlPlane3EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string

  # ---------------------------------------------------------------------------
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  # ---------------------------------------------------------------------------
resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              # ---------------------------------------------------------------------------
              # ctlplane interface
              # ---------------------------------------------------------------------------
              - type: interface
                name: nic1
                use_dhcp: false
                dns_servers:
                  get_param: DnsServers
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlane1SubnetCidr
                routes:
                - ip_netmask: 169.254.169.254/32
                  next_hop:
                    get_param: ControlPlane1EC2MetadataIp
                - default: true
                  next_hop:
                    get_param: ControlPlane1DefaultRoute
              # ---------------------------------------------------------------------------
              # VLAN trunk OVS bridge - Storage, Tenant
              # ---------------------------------------------------------------------------
              - type: ovs_bridge
                name: br-ex
                use_dhcp: false
                members:
                - type: interface
                  name: nic3
                  # force the MAC address of the bridge to this interface
                  primary: true
                - type: vlan
                  vlan_id:
                    get_param: Storage1NetworkVlanID
                  addresses:
                  - ip_netmask:
                      get_param: Storage1IpSubnet
                  routes:
                  - ip_netmask:
                      get_param: StorageSupernet
                    next_hop:
                      get_param: Storage1InterfaceDefaultRoute
                - type: vlan
                  vlan_id:
                    get_param: InternalApi1NetworkVlanID
                  addresses:
                  - ip_netmask:
                      get_param: InternalApi1IpSubnet
                  routes:
                  - ip_netmask:
                      get_param: InternalApiSupernet
                    next_hop:
                      get_param: InternalApi1InterfaceDefaultRoute
                - type: vlan
                  vlan_id:
                    get_param: Tenant1NetworkVlanID
                  addresses:
                  - ip_netmask:
                      get_param: Tenant1IpSubnet
                  routes:
                  - ip_netmask:
                      get_param: TenantSupernet
                    next_hop:
                      get_param: Tenant1InterfaceDefaultRoute
              # ---------------------------------------------------------------------------
outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl