undercloud_generate_service_certificate: false
undercloud_clean_nodes: true
ssl_overcloud: false
undercloud_docker_registry_mirror: http://10.12.50.1:5000
step_introspect: false
containerized_overcloud: true
enable_pacemaker: true
overcloud_ipv6: true

undercloud_enable_ui: false

telemetry_args: >-
   -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml

extra_args: >-
  --ntp-server clock.redhat.com
test_ping: true
modify_image_vc_verbose: true
modify_image_vc_root_password: redhat

# Use local mirror for images
overcloud_image_url: http://10.12.50.1/pub/tripleo-masterclass/queens-tripleo/overcloud-full.tar
ipa_image_url: http://10.12.50.1/pub/tripleo-masterclass/queens-tripleo/ironic-python-agent.tar
undercloud_image_url: http://10.12.50.1/pub/tripleo-masterclass/queens-tripleo/undercloud.qcow2

undercloud_network_cidr: 192.168.24.0/24
#undercloud_network_gateway: 192.168.24.1
#undercloud_undercloud_public_vip: 192.168.24.2
#undercloud_undercloud_admin_vip: 192.168.24.3
#undercloud_local_interface: eth1
#undercloud_masquerade_network: 192.168.24.0/24
#undercloud_dhcp_start: 192.168.24.5
#undercloud_dhcp_end: 192.168.24.24
#undercloud_inspection_iprange: 192.168.24.25,192.168.24.39
#undercloud_external_network_cidr: 10.0.0.0/24


overcloud_dns_servers: ["10.12.50.1" ] 
network_environment_args:
  ExternalInterfaceDefaultRoute: "2001:db8:fd00:1000::1"
  ExternalNetCidr: "2001:db8:fd00:1000::/64"
  ExternalAllocationPools: [{'end': '2001:db8:fd00:1000:ffff:ffff:ffff:fffe', 'start': '2001:db8:fd00:1000::10'}]
  NeutronExternalNetworkBridge: ""
  ControlPlaneSubnetCidr: "{{ undercloud_network_cidr|ipaddr('prefix') }}"
  ControlPlaneDefaultRoute: "{{ undercloud_network_cidr|nthhost(1) }}"
  EC2MetadataIp: "{{ undercloud_network_cidr|nthhost(1) }}"
  InternalApiNetCidr: "fd00:fd00:fd00:2000::/64"
  InternalApiAllocationPools: [{"start": "fd00:fd00:fd00:2000::10", "end": "fd00:fd00:fd00:2000:ffff:ffff:ffff:fffe"}]
  StorageNetCidr: "fd00:fd00:fd00:3000::/64"
  StorageAllocationPools: [{"start": "fd00:fd00:fd00:3000::10", "end": "fd00:fd00:fd00:3000:ffff:ffff:ffff:fffe"}]
  StorageMgmtNetCidr: "fd00:fd00:fd00:4000::/64"
  StorageMgmtAllocationPools: [{"start": "fd00:fd00:fd00:4000::10", "end": "fd00:fd00:fd00:4000:ffff:ffff:ffff:fffe"}]
  TenantNetCidr: 172.16.0.0/24
  TenantAllocationPools: [{"start": "172.16.0.10", "end": "172.16.0.250"}]
  DnsServers: "{{ overcloud_dns_servers }}"
  PublicVirtualFixedIPs: [{ "ip_address": "{{ undercloud_external_network_cidr|nthhost(5) }}" }]

network_isolation: true
network_isolation_type: 'single-nic-vlans'
network_isolation_args: >-
  -e {{ overcloud_templates_path }}/environments/network-isolation-v6.yaml
  -e {{ overcloud_templates_path }}/environments/net-single-nic-with-vlans-v6.yaml
  -e {{ working_dir }}/network-environment.yaml

topology: >-
  --compute-scale 1
  --control-scale 3
  --ceph-storage-scale 0
