parameter_defaults:
    # -------------------------------------------------------------------------
    # Control Plane subnet is used to get the VIPs,
    #    VIPs need to be on same network as controllers.
    # -------------------------------------------------------------------------
    ControlPlaneSubnet: ctlplane1

    # -------------------------------------------------------------------------
    # ExternalNetName is hardcoded in THT/puppet/all-nodes-config.j2.yaml
    #
    # -------------------------------------------------------------------------
    ExternalNetName: External1


    # -------------------------------------------------------------------------
    # Controller Node role - subnet mapping
    # -------------------------------------------------------------------------
    Controller1ControlPlaneSubnet: ctlplane1

    # -------------------------------------------------------------------------
    # Compute Node roles - subnet mapping
    # -------------------------------------------------------------------------
    Compute1ControlPlaneSubnet: ctlplane1
    Compute2ControlPlaneSubnet: ctlplane2
    Compute3ControlPlaneSubnet: ctlplane3

    # -------------------------------------------------------------------------
    # Ceph Node roles - subnet mapping
    # -------------------------------------------------------------------------
    CephStorage1ControlPlaneSubnet: ctlplane1
    CephStorage2ControlPlaneSubnet: ctlplane2
    CephStorage3ControlPlaneSubnet: ctlplane3

    # -------------------------------------------------------------------------
    # Control Plane route and ip subnet prefix for:
    #     ctlplane0, ctlplane1, ctlplane2 and ctlplane3
    # -------------------------------------------------------------------------
    ControlPlane0DefaultRoute: 172.20.0.62
    ControlPlane0SubnetCidr: '26'
    ControlPlane1DefaultRoute: 172.20.0.126
    ControlPlane1SubnetCidr: '26'
    ControlPlane2DefaultRoute: 172.20.0.190
    ControlPlane2SubnetCidr: '26'
    ControlPlane3DefaultRoute: 172.20.0.254
    ControlPlane3SubnetCidr: '26'

    DnsServers:
    - 10.12.50.1

    # -------------------------------------------------------------------------
    # EC2MetadataIp's
    # -------------------------------------------------------------------------
    # The metadata ip address for the leaf local
    # to the undercloud is the main undercloud ip.
    # For the remote (non-local) leafs, the routed
    # network infra need a route to 169.254.169.254
    # via routers to the undercloud main ip.
    # -------------------------------------------------------------------------
    ControlPlane0EC2MetadataIp: 172.20.0.1
    ControlPlane1EC2MetadataIp:  172.20.0.126
    ControlPlane2EC2MetadataIp:  172.20.0.190
    ControlPlane3EC2MetadataIp:  172.20.0.254

    # -------------------------------------------------------------------------
    # Supernets
    # -------------------------------------------------------------------------
    # These are Supernet CIDR's used in the routing tables.
    # Supernets allow a single routing table entry for multiple
    # adjecent networks.
    # -------------------------------------------------------------------------
    ExternalSupernet: 172.20.2.0/26
    InternalApiSupernet: 172.20.1.0/24
    StorageSupernet: 172.20.3.0/24
    StorageMgmtSupernet: 172.20.4.0/24
    TenantSupernet: 172.20.5.0/24
    CtlplaneSupernet: 172.20.0.0/24

    # -------------------------------------------------------------------------
    # External Networks
    # -------------------------------------------------------------------------
    External1InterfaceDefaultRoute: 172.20.2.126
    External1AllocationPools:
    -   start: 172.20.2.80
        end: 172.20.2.99
    External1NetCidr: 172.20.2.64/24
    External1NetworkVlanID: 621

    # -------------------------------------------------------------------------
    # Internal Api Networks
    # -------------------------------------------------------------------------
    InternalApi0InterfaceDefaultRoute: 172.20.1.62
    InternalApi0AllocationPools:
    -   start: 172.20.1.10
        end: 172.20.1.29
    InternalApi0NetCidr: 172.20.1.0/26
    InternalApi0NetworkVlanID: 610

    InternalApi1InterfaceDefaultRoute: 172.20.1.126
    InternalApi1AllocationPools:
    -   start: 172.20.1.80
        end: 172.20.1.99
    InternalApi1NetCidr: 172.20.1.64/26
    InternalApi1NetworkVlanID: 611

    InternalApi2InterfaceDefaultRoute: 172.20.1.190
    InternalApi2AllocationPools:
    -   start: 172.20.1.140
        end: 172.20.1.159
    InternalApi2NetCidr: 172.20.1.128/26
    InternalApi2NetworkVlanID: 612

    InternalApi3InterfaceDefaultRoute: 172.20.1.254
    InternalApi3AllocationPools:
    -   start: 172.20.1.210
        end: 172.20.1.229
    InternalApi3NetCidr: 172.20.1.192/26
    InternalApi3NetworkVlanID: 613

    # -------------------------------------------------------------------------
    # Storage Networks
    # -------------------------------------------------------------------------
    Storage0InterfaceDefaultRoute: 172.20.3.62
    Storage0AllocationPools:
    -   start: 172.20.3.10
        end: 172.20.3.29
    Storage0NetCidr: 172.20.3.0/26
    Storage0NetworkVlanID: 639

    Storage1InterfaceDefaultRoute: 172.20.3.126
    Storage1AllocationPools:
    -   start: 172.20.3.80
        end: 172.20.3.99
    Storage1NetCidr: 172.20.3.64/26
    Storage1NetworkVlanID: 631

    Storage2InterfaceDefaultRoute: 172.20.3.190
    Storage2AllocationPools:
    -   start: 172.20.3.140
        end: 172.20.3.159
    Storage2NetCidr: 172.20.3.128/26
    Storage2NetworkVlanID: 632

    Storage3InterfaceDefaultRoute: 172.20.3.254
    Storage3AllocationPools:
    -   start: 172.20.3.219
        end: 172.20.3.229
    Storage3NetCidr: 172.20.3.192/26
    Storage3NetworkVlanID: 633

    # -------------------------------------------------------------------------
    # Storage Management Networks
    # -------------------------------------------------------------------------
    StorageMgmt0InterfaceDefaultRoute: 172.20.4.62
    StorageMgmt0AllocationPools:
    -   start: 172.20.4.10
        end: 172.20.4.29
    StorageMgmt0NetCidr: 172.20.4.0/26
    StorageMgmt0NetworkVlanID: 640

    StorageMgmt1InterfaceDefaultRoute: 172.20.4.126
    StorageMgmt1AllocationPools:
    -   start: 172.20.4.80
        end: 172.20.4.99
    StorageMgmt1NetCidr: 172.20.4.64/26
    StorageMgmt1NetworkVlanID: 641

    StorageMgmt2InterfaceDefaultRoute: 172.20.4.190
    StorageMgmt2AllocationPools:
    -   start: 172.20.4.140
        end: 172.20.4.159
    StorageMgmt2NetCidr: 172.20.4.128/26
    StorageMgmt2NetworkVlanID: 642

    StorageMgmt3InterfaceDefaultRoute: 172.20.4.254
    StorageMgmt3AllocationPools:
    -   start: 172.20.4.210
        end: 172.20.4.229
    StorageMgmt3NetCidr: 172.20.4.192/26
    StorageMgmt3NetworkVlanID: 643

    # -------------------------------------------------------------------------
    # Tenant Networks
    # -------------------------------------------------------------------------
    Tenant0InterfaceDefaultRoute: 172.20.5.62
    Tenant0AllocationPools:
    -   start: 172.20.5.10
        end: 172.20.5.29
    Tenant0NetCidr: 172.20.5.0/26
    Tenant0NetworkVlanID: 650

    Tenant1InterfaceDefaultRoute: 172.20.5.126
    Tenant1AllocationPools:
    -   start: 172.20.5.80
        end: 172.20.5.99
    Tenant1NetCidr: 172.20.5.64/26
    Tenant1NetworkVlanID: 651

    Tenant2InterfaceDefaultRoute: 172.20.5.190
    Tenant2AllocationPools:
    -   start: 172.20.5.140
        end: 172.20.5.159
    Tenant2NetCidr: 172.20.5.128/26
    Tenant2NetworkVlanID: 652

    Tenant3InterfaceDefaultRoute: 172.20.5.254
    Tenant3AllocationPools:
    -   start: 172.20.5.210
        end: 172.20.5.229
    Tenant3NetCidr: 172.20.5.192/26
    Tenant3NetworkVlanID: 653


    NeutronBridgeMappings: datacentre:br-ex,tenant:br-isolated
    NeutronExternalNetworkBridge: ''
    NeutronNetworkType: vxlan
    NeutronNetworkVLANRanges: tenant:1000:2000
    NeutronTunnelTypes: vxlan

    ServiceNetMap:
        ApacheNetwork: internal_api1
        NeutronTenantNetwork: tenant1
        CeilometerApiNetwork: internal_api1
        AodhApiNetwork: internal_api1
        PankoApiNetwork: internal_api1
        BarbicanApiNetwork: internal_api1
        GnocchiApiNetwork: internal_api1
        MongodbNetwork: internal_api1
        CinderApiNetwork: internal_api1
        CinderIscsiNetwork: storage1
        CongressApiNetwork: internal_api1
        GlanceApiNetwork: internal_api1
        IronicApiNetwork: ctlplane
        IronicNetwork: ctlplane
        IronicInspectorNetwork: ctlplane
        KeystoneAdminApiNetwork: ctlplane # allows undercloud to config endpoints
        KeystonePublicApiNetwork: internal_api1
        ManilaApiNetwork: internal_api1
        NeutronApiNetwork: internal_api1
        OctaviaApiNetwork: internal_api1
        HeatApiNetwork: internal_api1
        HeatApiCfnNetwork: internal_api1
        HeatApiCloudwatchNetwork: internal_api1
        NovaApiNetwork: internal_api1
        NovaPlacementNetwork: internal_api1
        NovaMetadataNetwork: internal_api1
        NovaVncProxyNetwork: internal_api1
        NovaLibvirtNetwork: internal_api1
        NovajoinNetwork: internal_api1
        Ec2ApiNetwork: internal_api1
        Ec2ApiMetadataNetwork: internal_api1
        TackerApiNetwork: internal_api1
        SwiftStorageNetwork: storage_mgmt1
        SwiftProxyNetwork: storage1
        SaharaApiNetwork: internal_api1
        HorizonNetwork: internal_api1
        MemcachedNetwork: internal_api1
        OsloMessagingRpcNetwork: internal_api1
        OsloMessagingNotifyNetwork: internal_api1
        RabbitmqNetwork: internal_api1
        QdrNetwork: internal_api1
        RedisNetwork: internal_api1
        GaneshaNetwork: storage_nfs
        MysqlNetwork: internal_api1
        SnmpdNetwork: internal_api1
        CephClusterNetwork: storage_mgmt
        CephMonNetwork: storage1
        CephRgwNetwork: storage1
        PublicNetwork: external1
        OpendaylightApiNetwork: internal_api1
        OvnDbsNetwork: internal_api1
        MistralApiNetwork: internal_api1
        ZaqarApiNetwork: internal_api1
        DockerRegistryNetwork: ctlplane
        PacemakerRemoteNetwork: internal_api1
        TripleoUINetwork: internal_api1
        DesignateApiNetwork: internal_api1
        # We special-case the default ResolveNetwork for the CephStorage role
        # for backwards compatibility, all other roles default to internal_api
        CephStorage1HostnameResolveNetwork: storage1
        CephStorage2HostnameResolveNetwork: storage2
        CephStorage3HostnameResolveNetwork: storage3
        EtcdNetwork: internal_api
        #{% for role in roles if role.name != 'CephStorage' %}
        #   {{role.name}}HostnameResolveNetwork: internal_api
        #{% endfor %}
        Controller1HostnameResolveNetwork: internal_api1
        Compute1HostnameResolveNetwork: internal_api1
        Compute2HostnameResolveNetwork: internal_api2
        Compute3HostnameResolveNetwork: internal_api3



resource_registry:
    #--------------------------------------------------------------------------
    # Controller Nodes
    OS::TripleO::Controller1::Net::SoftwareConfig: /home/stack/templates/nic-config/control1.yaml
    #--------------------------------------------------------------------------
    # Ceph Storage Nodes
    OS::TripleO::CephStorage0::Net::SoftwareConfig: /home/stack/templates/nic-config/ceph0.yaml
    OS::TripleO::CephStorage1::Net::SoftwareConfig: /home/stack/templates/nic-config/ceph1.yaml
    OS::TripleO::CephStorage2::Net::SoftwareConfig: /home/stack/templates/nic-config/ceph2.yaml
    OS::TripleO::CephStorage3::Net::SoftwareConfig: /home/stack/templates/nic-config/ceph3.yaml
    #--------------------------------------------------------------------------
    # Compute Nodes
    OS::TripleO::Compute0::Net::SoftwareConfig: /home/stack/templates/nic-config/compute0.yaml
    OS::TripleO::Compute1::Net::SoftwareConfig: /home/stack/templates/nic-config/compute1.yaml
    OS::TripleO::Compute2::Net::SoftwareConfig: /home/stack/templates/nic-config/compute2.yaml
    OS::TripleO::Compute3::Net::SoftwareConfig: /home/stack/templates/nic-config/compute3.yaml